Name:           ros-indigo-pr2-map-navigation-app
Version:        1.0.2
Release:        0%{?dist}
Summary:        ROS pr2_map_navigation_app package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/map_nav
Source0:        %{name}-%{version}.tar.gz

Requires:       mongodb
Requires:       ros-indigo-amcl
Requires:       ros-indigo-map-store
Requires:       ros-indigo-pr2-machine
Requires:       ros-indigo-pr2-navigation-config
Requires:       ros-indigo-pr2-navigation-global
Requires:       ros-indigo-pr2-navigation-perception
Requires:       ros-indigo-pr2-navigation-teleop
Requires:       ros-indigo-pr2-position-scripts
Requires:       ros-indigo-tf
Requires:       ros-indigo-topic-tools
BuildRequires:  mongodb
BuildRequires:  ros-indigo-amcl
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-map-store
BuildRequires:  ros-indigo-pr2-machine
BuildRequires:  ros-indigo-pr2-navigation-config
BuildRequires:  ros-indigo-pr2-navigation-global
BuildRequires:  ros-indigo-pr2-navigation-perception
BuildRequires:  ros-indigo-pr2-navigation-teleop
BuildRequires:  ros-indigo-pr2-position-scripts
BuildRequires:  ros-indigo-tf
BuildRequires:  ros-indigo-topic-tools

%description
Map nav for the PR2.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Tue Feb 10 2015 Devon Ash <dash@clearpathrobotics.com> - 1.0.2-0
- Autogenerated by Bloom

